import { ArrowLeft, Download, MessageCircle, ReceiptText, RefreshCcw, Star } from "lucide-react";
import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { CompletionModal } from "../../components/feedback/CompletionModal";
import { Timeline } from "../../components/errand/Timeline";
import { Avatar, Badge, Button, Card, IconButton, PageHeader } from "../../components/ui";
import { errands, runners } from "../../data/mockData";
import { formatKES } from "../../services/mockApi";
import { useAppStore } from "../../store/appStore";

export function ActivityDetailPage(){const {id}=useParams();const nav=useNavigate();const {addToast}=useAppStore();const [rate,setRate]=useState(false);const errand=errands.find(e=>e.id===id)||errands[0];const runner=errand.runner||runners[0];return <div className="standard-page detail-page"><PageHeader eyebrow={errand.date} title={errand.title} back={<IconButton label="Back" onClick={()=>nav(-1)}><ArrowLeft size={20}/></IconButton>} action={<Badge tone={errand.status==="completed"?"green":"blue"}>{errand.status}</Badge>}/><div className="detail-grid"><section><Card className="detail-summary"><Badge tone="neutral">{errand.category}</Badge><p>{errand.description}</p><div className="review-route detail-route"><div><span className="route-origin"/><small>Pickup</small><b>{errand.pickup}</b></div><i><span>{errand.distance}</span></i><div><span className="route-dest"/><small>Destination</small><b>{errand.destination}</b></div></div><div className="detail-money"><span>Agreed price <b>{formatKES(errand.budget)}</b></span><span>Date <b>{errand.date}</b></span></div></Card><Card className="receipt-card"><ReceiptText size={21}/><div><b>Errand receipt</b><p>Reference TU-1048 · Settled</p></div><Button variant="ghost" size="sm" icon={<Download size={16}/>} onClick={()=>addToast("Receipt downloaded.")}>Download</Button></Card></section><aside><Card className="detail-runner"><Avatar initials={runner.initials} src={runner.photo} size="lg" color={runner.color}/><div><h3>{runner.name}</h3><p>★ {runner.rating} · Verified runner</p></div><Button variant="secondary" size="sm" icon={<MessageCircle size={16}/>} onClick={()=>nav(`/messages/${runner.id}`)}>Message</Button></Card><Card className="detail-timeline"><h3>Status history</h3><Timeline activeStatus={errand.status==="completed"?7:4} compact/></Card></aside></div><div className="sticky-page-actions"><Button variant="secondary" icon={<RefreshCcw size={17}/>} onClick={()=>nav("/post")}>Repeat errand</Button>{errand.status==="completed"&&<Button icon={<Star size={17}/>} onClick={()=>setRate(true)}>Rate runner</Button>}</div><CompletionModal open={rate} onClose={()=>setRate(false)}/></div>}
