import { Bell, CheckCheck, CircleDollarSign, Clock3, MessageCircle, PackageCheck, Star, UserCheck } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Badge, Button, EmptyState, PageHeader, Tabs } from "../../components/ui";
import { useAppStore } from "../../store/appStore";

type Filter="all"|"unread";
const items=[{id:1,icon:UserCheck,title:"Brian sent you an offer",copy:"KES 750 · Arrives in 6 minutes",time:"2 min ago",unread:true,to:"/offers/new",tone:"green"},{id:2,icon:PackageCheck,title:"Your runner has arrived",copy:"Brian is at Sarit Centre reception.",time:"18 min ago",unread:true,to:"/tracking/errand-1",tone:"blue"},{id:3,icon:MessageCircle,title:"New message from Brian",copy:"Package secured. Starting delivery…",time:"24 min ago",unread:true,to:"/messages/brian-kamau",tone:"dark"},{id:4,icon:CircleDollarSign,title:"Errand price confirmed",copy:"Your agreed price is KES 750.",time:"30 min ago",unread:false,to:"/activity/errand-1",tone:"amber"},{id:5,icon:Star,title:"How did Aisha do?",copy:"Rate your recent hardware store errand.",time:"Yesterday",unread:false,to:"/activity/errand-5",tone:"amber"},{id:6,icon:CheckCheck,title:"Errand completed",copy:"Your store run was delivered successfully.",time:"Yesterday",unread:false,to:"/activity/errand-5",tone:"green"}];
export function NotificationsPage(){const nav=useNavigate();const [filter,setFilter]=useState<Filter>("all");const {unreadNotifications,markNotificationsRead,addToast}=useAppStore();const filtered=filter==="unread"?items.filter(i=>i.unread&&unreadNotifications>0):items;return <div className="standard-page notifications-page"><PageHeader eyebrow="Stay in the loop" title="Notifications" action={<Button variant="ghost" icon={<CheckCheck size={17}/>} onClick={()=>{markNotificationsRead();addToast("All notifications marked as read.")}}>Mark all read</Button>}/><Tabs value={filter} onChange={setFilter} options={[{value:"all",label:"All",count:items.length},{value:"unread",label:"Unread",count:unreadNotifications}]}/>{filtered.length?<div className="notification-list">{filtered.map(item=><button key={item.id} className={item.unread&&unreadNotifications>0?"unread":""} onClick={()=>nav(item.to)}><span className={`notification-icon tone-${item.tone}`}><item.icon size={19}/></span><div><b>{item.title}{item.unread&&unreadNotifications>0&&<i/>}</b><p>{item.copy}</p><small><Clock3 size={13}/>{item.time}</small></div><Badge tone="neutral">View</Badge></button>)}</div>:<EmptyState icon={<Bell/>} title="You’re all caught up" description="New offers, status changes and messages will show up here."/>}</div>}
