import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, CalendarDays, Camera, Check, Clock3, LocateFixed, MapPin, Navigation, Plus, Sparkles, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { categories } from "../../data/mockData";
import { useAppStore } from "../../store/appStore";
import type { Category } from "../../types";
import { Badge, Button, Card, IconButton, Input, SegmentedControl, Textarea, cn } from "../../components/ui";

const steps = ["Task", "Category", "Pickup", "Destination", "Timing", "Budget", "Details", "Review"];
const templates = ["Pick up my laptop charger from Westlands and bring it to Kilimani.", "Collect my documents from the office.", "Buy groceries and deliver them."];

export function PostErrand() {
  const navigate = useNavigate(); const location = useLocation(); const { draft, updateDraft, addToast } = useAppStore();
  const [step, setStep] = useState(0); const [direction, setDirection] = useState(1);
  useEffect(() => { const selected = (location.state as { category?: Category } | null)?.category; if (selected) { updateDraft({ category: selected }); setStep(2); } }, [location.state, updateDraft]);
  const next = () => { if (step < 7) { setDirection(1); setStep(step + 1); } else { addToast("Errand posted. Finding nearby runners…"); navigate("/offers/new"); } };
  const back = () => { if (step > 0) { setDirection(-1); setStep(step - 1); } else navigate(-1); };
  const validByStep = [draft.task.trim().length > 10, Boolean(draft.category), draft.pickup.trim().length > 3, draft.destination.trim().length > 3, draft.when !== "Schedule" || Boolean(draft.scheduleDate), draft.budget >= 200, true, true];
  const valid = validByStep[step];
  return <div className="post-page">
    <header className="post-header"><IconButton label="Go back" onClick={back}><ArrowLeft size={20}/></IconButton><div><span>Post an errand</span><b>{step + 1} of {steps.length}</b></div><button onClick={() => navigate("/")}>Save & exit</button></header>
    <div className="step-progress"><motion.span animate={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div>
    <div className="post-shell"><aside className="step-sidebar"><h2>Let’s get it moving.</h2><p>Give runners enough detail to make a confident offer.</p><div>{steps.map((item, index) => <button key={item} className={cn(index === step && "active", index < step && "done")} onClick={() => index < step && setStep(index)}><span>{index < step ? <Check size={14}/> : index + 1}</span>{item}</button>)}</div><div className="post-help"><Sparkles size={18}/><p><b>Clear errands get faster offers.</b><span>Include landmarks or collection details where useful.</span></p></div></aside>
      <section className="step-content"><AnimatePresence mode="wait" custom={direction}><motion.div key={step} custom={direction} initial={{ opacity: 0, x: direction * 28 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: direction * -20 }} transition={{ duration: .23 }} className="step-panel">
        {step === 0 && <><div className="step-title"><Badge tone="green">Start here</Badge><h1>What do you need done?</h1><p>Describe the outcome in your own words. You can add the details next.</p></div><Textarea autoFocus rows={5} maxLength={240} value={draft.task} onChange={(e) => updateDraft({ task: e.target.value })} placeholder="e.g. Pick up a package and bring it to me…" /><span className="char-count">{draft.task.length} / 240</span><div className="suggestions"><p>Try a suggestion</p>{templates.map((template) => <button type="button" key={template} onClick={() => updateDraft({ task: template })}>{template}<ArrowRight size={16}/></button>)}</div></>}
        {step === 1 && <><div className="step-title"><h1>Choose a category</h1><p>This helps us match you with runners who do this well.</p></div><div className="category-choice-grid">{categories.map((category) => <button key={category.name} className={cn(draft.category === category.name && "selected")} onClick={() => updateDraft({ category: category.name })}><span className="category-choice-photo"><img src={category.image} alt="" /></span><b>{category.name}</b>{draft.category === category.name && <Check size={17}/>}</button>)}</div></>}
        {step === 2 && <LocationStep title="Where should the runner start?" subtitle="Add the exact pickup point or a nearby landmark." value={draft.pickup} onChange={(pickup) => updateDraft({ pickup })} type="pickup" />}
        {step === 3 && <LocationStep title="Where is it going?" subtitle="Add the final hand-off location." value={draft.destination} onChange={(destination) => updateDraft({ destination })} type="destination" />}
        {step === 4 && <><div className="step-title"><h1>When do you need it?</h1><p>Runners will see the timing before they make an offer.</p></div><SegmentedControl value={draft.when} onChange={(when) => updateDraft({ when })} options={[{value:"Now",label:"Now"},{value:"Today",label:"Later today"},{value:"Schedule",label:"Schedule"}]} />{draft.when === "Schedule" && <Card className="schedule-card"><Input type="date" label="Date" value={draft.scheduleDate} onChange={(e) => updateDraft({scheduleDate:e.target.value})} icon={<CalendarDays size={18}/>} /><Input type="time" label="Preferred time" defaultValue="10:00" icon={<Clock3 size={18}/>} /></Card>}<div className="timing-note"><Clock3 size={20}/><div><b>{draft.when === "Now" ? "Matching begins immediately" : draft.when === "Today" ? "Choose a runner now, complete it today" : "Offers stay open until you choose"}</b><p>You’re always in control of who takes the errand.</p></div></div></>}
        {step === 5 && <><div className="step-title"><h1>Set your budget</h1><p>Based on distance, timing and similar errands.</p></div><div className="price-input"><span>KES</span><input type="number" min="200" max="50000" inputMode="numeric" value={draft.budget} onChange={(e) => updateDraft({ budget: Number(e.target.value) })} aria-label="Budget" /></div><div className="range-visual"><div className="range-labels"><span>KES 550</span><b>Suggested: KES 650–850</b><span>KES 1,000</span></div><div className="range-track"><span/><motion.i animate={{left:`${Math.min(92, Math.max(8, ((draft.budget-500)/600)*100))}%`}} /></div></div><div className="quick-prices">{[600,750,850,1000].map((price)=><button type="button" key={price} onClick={()=>updateDraft({budget:price})} className={cn(draft.budget===price&&"selected")}>KES {price}</button>)}</div><Card className="budget-tip"><Sparkles size={20}/><p><b>KES 750 is likely to get a quick response.</b><span>Runners can still send a different offer.</span></p></Card></>}
        {step === 6 && <><div className="step-title"><h1>Add helpful details</h1><p>A little context makes pickup and hand-off smoother.</p></div><Textarea label="Instructions" rows={4} value={draft.instructions} onChange={(e)=>updateDraft({instructions:e.target.value})} /><Textarea label="Contact instructions (optional)" rows={3} value={draft.contact} onChange={(e)=>updateDraft({contact:e.target.value})} /><div className="upload-zone"><Camera size={24}/><div><b>Add reference photos</b><span>Receipts, item photos or pickup details</span></div><Button variant="secondary" size="sm" icon={<Plus size={16}/>} onClick={()=>{updateDraft({photos:[...draft.photos,"item-reference.jpg"]});addToast("Reference photo added.")}}>Add photo</Button></div>{draft.photos.map((photo)=><div className="file-pill" key={photo}><Camera size={16}/>{photo}<button onClick={()=>updateDraft({photos:[]})}><X size={15}/></button></div>)}</>}
        {step === 7 && <Review draft={draft} edit={setStep}/>} 
      </motion.div></AnimatePresence>
      <footer className="step-footer"><Button variant="ghost" onClick={back}>{step === 0 ? "Cancel" : "Back"}</Button><Button size="lg" disabled={!valid} onClick={next}>{step === 7 ? "Find a Runner" : "Continue"}<ArrowRight size={18}/></Button></footer></section>
    </div>
  </div>;
}

function LocationStep({ title, subtitle, value, onChange, type }: { title:string; subtitle:string; value:string; onChange:(value:string)=>void; type:"pickup"|"destination" }) {
  const locations=["Sarit Centre, Westlands","Yaya Centre, Kilimani","Lavington Mall","Kenyatta Avenue, CBD"];
  return <><div className="step-title"><h1>{title}</h1><p>{subtitle}</p></div><Input value={value} onChange={(e)=>onChange(e.target.value)} icon={type==="pickup"?<LocateFixed size={19}/>:<MapPin size={19}/>} placeholder="Search for a place or address"/><div className="location-preview-card"><div className="mini-map-preview"><span className={type}/></div><div><small>{type === "pickup" ? "Pickup point" : "Destination"}</small><b>{value || "Choose a location"}</b><p>Nairobi, Kenya</p></div><Navigation size={18}/></div><div className="location-suggestions"><p>Recent places</p>{locations.map((location)=><button key={location} onClick={()=>onChange(location)}><MapPin size={17}/><span>{location}<small>Nairobi</small></span><ArrowRight size={15}/></button>)}</div></>;
}

function Review({ draft, edit }: { draft: ReturnType<typeof useAppStore.getState>["draft"]; edit:(step:number)=>void }) {
  const details=[{label:"Task",value:draft.task,step:0},{label:"Category",value:draft.category,step:1},{label:"Pickup",value:draft.pickup,step:2},{label:"Destination",value:draft.destination,step:3},{label:"When",value:draft.when,step:4},{label:"Budget",value:`KES ${draft.budget.toLocaleString()}`,step:5}];
  return <><div className="step-title"><Badge tone="green">Ready to post</Badge><h1>Review your errand</h1><p>Check the details before we start matching you.</p></div><div className="review-route"><div><span className="route-origin"/><small>Pickup</small><b>{draft.pickup}</b></div><i><span>6.4 km</span></i><div><span className="route-dest"/><small>Destination</small><b>{draft.destination}</b></div></div><div className="review-list">{details.map((item)=><button key={item.label} onClick={()=>edit(item.step)}><span>{item.label}</span><b>{item.value}</b><small>Edit</small></button>)}</div>{draft.instructions&&<Card className="review-notes"><small>Instructions</small><p>{draft.instructions}</p></Card>}<div className="review-assurance"><Check size={16}/><span>You won’t be charged until you choose a runner.</span></div></>;
}
