import { Compass, Filter, List, Map, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { ErrandCard } from "../../components/cards/ErrandCard";
import { MockMap } from "../../components/maps/MockMap";
import { Badge, Button, Card, EmptyState, Modal, PageHeader, SearchInput, SegmentedControl, Switch } from "../../components/ui";
import { errands } from "../../data/mockData";
import { useAppStore } from "../../store/appStore";

type View="list"|"map";
export function NearbyErrandsPage(){const [view,setView]=useState<View>("list");const [search,setSearch]=useState("");const [filter,setFilter]=useState(false);const [urgent,setUrgent]=useState(false);const {online,toggleOnline}=useAppStore();const nearby=errands.filter(e=>e.status==="open"&&(!urgent||e.urgency==="URGENT")&&(e.title+e.pickup).toLowerCase().includes(search.toLowerCase()));return <div className="standard-page nearby-page"><PageHeader eyebrow="Fresh opportunities" title="Nearby errands" action={<div className="nearby-online"><span>{online?"Online":"Offline"}</span><Switch checked={online} onChange={toggleOnline} label="Online status"/></div>}/><div className="nearby-toolbar"><SearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search area or task"/><Button variant="secondary" icon={<SlidersHorizontal size={17}/>} onClick={()=>setFilter(true)}>Filters</Button><SegmentedControl value={view} onChange={setView} options={[{value:"list",label:"List"},{value:"map",label:"Map"}]} compact/></div><div className={`nearby-layout view-${view}`}><section className="nearby-list"><div className="nearby-result-head"><p><b>{nearby.length} errands</b> within 5 km</p><Badge tone="green"><Compass size={14}/> Best match first</Badge></div>{nearby.length?nearby.map(errand=><ErrandCard key={errand.id} errand={errand} runnerView/>):<EmptyState icon={<Search/>} title="No nearby jobs found" description="Try a wider radius or switch off urgent-only filtering." action={<Button onClick={()=>{setUrgent(false);setSearch("")}}>Expand search radius</Button>}/>}</section><aside className="nearby-map"><MockMap variant="nearby" showSearch/><div className="map-job-preview"><Badge tone="red">URGENT</Badge><b>Deliver signed documents</b><span><MapPin size={14}/> 1.4 km away · KES 650</span></div></aside></div><Modal open={filter} onClose={()=>setFilter(false)} title="Filter nearby errands" footer={<><Button variant="ghost" onClick={()=>setUrgent(false)}>Reset</Button><Button onClick={()=>setFilter(false)}>Show {nearby.length} errands</Button></>}><div className="filter-content"><label>Working radius<select defaultValue="5"><option value="3">3 km</option><option value="5">5 km</option><option value="10">10 km</option></select></label><div className="filter-row"><span><b>Urgent only</b><small>Show errands needed right now</small></span><Switch checked={urgent} onChange={()=>setUrgent(!urgent)} label="Urgent only"/></div><label>Minimum budget<select defaultValue="400"><option>KES 400</option><option>KES 600</option><option>KES 800</option></select></label></div></Modal></div>}
