import { ArrowLeft, CheckCheck, ChevronRight, MessageCircle, MoreVertical, Phone, Search, ShieldCheck, Video } from "lucide-react";
import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ChatThread } from "../../components/chat/ChatThread";
import { Avatar, Button, EmptyState, IconButton, PageHeader, SearchInput, cn } from "../../components/ui";
import { runners } from "../../data/mockData";
import { useAppStore } from "../../store/appStore";

const conversations=[{runner:runners[0],message:"Package secured. Starting delivery…",time:"10:48 AM",unread:2},{runner:runners[1],message:"Thank you! Have a lovely evening.",time:"Yesterday",unread:0},{runner:runners[3],message:"Yes, I’m available tomorrow morning.",time:"Sun",unread:0}];

export function MessagesPage({runnerMode=false}:{runnerMode?:boolean}){const params=useParams();const nav=useNavigate();const [search,setSearch]=useState("");const {addToast}=useAppStore();const activeId=params.id;const filtered=conversations.filter(c=>c.runner.name.toLowerCase().includes(search.toLowerCase()));const activeRunner=conversations.find(c=>c.runner.id===activeId)?.runner||runners[0];return <div className={cn("messages-page",activeId&&"conversation-open")}><aside className="conversation-list"><PageHeader eyebrow={runnerMode?"Runner inbox":"Your conversations"} title="Messages"/><SearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations"/>{filtered.length?<div className="conversation-items">{filtered.map(({runner,message,time,unread})=><button key={runner.id} onClick={()=>nav(`${runnerMode?"/runner/messages":"/messages"}/${runner.id}`)} className={cn(activeId===runner.id&&"active")}><Avatar initials={runner.initials} src={runner.photo} color={runner.color} online={runner.id===runners[0].id}/><div><b>{runner.name}{runner.verified&&<CheckCheck size={15}/>}</b><span>{message}</span></div><small>{time}{unread>0&&<i>{unread}</i>}</small></button>)}</div>:<EmptyState icon={<MessageCircle/>} title="No messages found" description="Try a different name or start a conversation from an errand."/>}</aside><section className="conversation-panel">{activeId?<><header className="chat-head"><IconButton label="Back to messages" className="chat-back" onClick={()=>nav(runnerMode?"/runner/messages":"/messages")}><ArrowLeft size={20}/></IconButton><Avatar initials={activeRunner.initials} src={activeRunner.photo} color={activeRunner.color} online/><div><b>{activeRunner.name} <CheckCheck size={15}/></b><span>Active now · Errand TU-1048</span></div><IconButton label="Call" onClick={()=>addToast(`Calling ${activeRunner.name.split(" ")[0]}…`,"info")}><Phone size={19}/></IconButton><IconButton label="Video call" onClick={()=>addToast("Video calling is unavailable in this demo.","info")}><Video size={19}/></IconButton><IconButton label="Conversation options"><MoreVertical size={19}/></IconButton></header><div className="chat-job-banner"><ShieldCheck size={18}/><div><b>Charger delivery</b><span>In progress · ETA 9 min</span></div><Button variant="ghost" size="sm" onClick={()=>nav(runnerMode?"/runner/jobs/errand-1":"/tracking/errand-1")}>View errand <ChevronRight size={15}/></Button></div><ChatThread recipientName={activeRunner.name.split(" ")[0]}/></>:<div className="no-conversation"><div><MessageCircle size={28}/></div><h2>Your conversations, all in one place.</h2><p>Select a conversation to coordinate pickup, share updates and get things done.</p><Button variant="secondary" icon={<Search size={17}/>} onClick={()=>document.querySelector<HTMLInputElement>(".conversation-list input")?.focus()}>Find a conversation</Button></div>}</section></div>}
